accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name= 'accounts'

urlpatterns = [
    path('signup', views.SignupView.as_view(), name='signup'),
    path('login', views.Login.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tweets.urls')),
    path('', include('accounts.urls')),
]

tweets/urls.py
from django.urls import path
from . import views

app_name= 'tweets'

urlpatterns = [
    path('', views.TimelineView.as_view(), name='timeline'),
    path('tweet/new/', views.TweetCreate.as_view(), name='tweet_new'),
]

accounts/models.py
from django.db import models

# Create your models here.

tweets/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Tweet(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField()
    created_time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.created_time.strftime('%Y-%m-%d %H:%M:%S')

accounts/views.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.views import generic


class SignupView(generic.CreateView):
    template_name = 'accounts/signup.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('accounts:login')


class Login(LoginView):
    template_name = 'accounts/login.html'
    form_class = AuthenticationForm
    success_url = reverse_lazy('tweets:timeline')

tweets/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic

from .models import Tweet
   

class TimelineView(generic.ListView):
    template_name = 'tweets/timeline.html'
    context_object_name = 'timeline'

    def get_queryset(self):
        return Tweet.objects.order_by('-created_time')


class TweetCreate(LoginRequiredMixin, generic.CreateView):
    template_name = 'tweets/tweet_new.html'
    success_url = reverse_lazy('tweets:timeline')
    model = Tweet
    fields = ['text']

    def form_valid(self, form):
        tweet = form.save(commit=False)
        tweet.author = self.request.user
        tweet.save()
        return super().form_valid(form)

accounts/templates/accounts/base.html
{% load static %}

<html>
  <head>
  </head>
  <body>
    <h1>つったかたー</h1>
    {% block content %}
    {% endblock %}
  </body>
</html>

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block content %}
<h2>login</h2>
<form method="POST">
{% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>
<p><a href="{% url 'accounts:signup' %}">sign up</a></p>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'accounts/base.html' %}

{% block content %}
<p>Sign up</p>
<form method="POST">
{% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>
{% endblock %}

tweets/templates/tweets/base.html
{% load static %}
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="{% static 'tweets/normalize.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'tweets/style.css' %}">
  </head>
  <body>
    <h1>つったかたー</h1>
    {% if user.is_authenticated %}
    <p class="menu"><a href="{% url 'tweets:tweet_new' %}">tweet_new</a></p>
    <p class="menu"><a href="{% url 'accounts:logout' %}">logout</a></p>
    {% endif %}
    {% block content %}
    {% endblock %}
  </body>
</html>

tweets/templates/tweets/timeline.html
{% extends 'tweets/base.html' %}

{% block content %}
  {% if timeline %}
    <div class="timeline">
    {% for tweet in timeline %}
      <div class="tweet">
        <p>{{ tweet.author }}</p>
        <p>{{ tweet.text }}</p>
        <p>{{ tweet.created_time }}</p>
      </div>
    {% endfor %}
    </div>
  {% else %}
    <p>no tweets</p>
  {% endif %}
{% endblock %}

tweets/templates/tweets/tweet_new.html
{% extends 'tweets/base.html' %}

{% block content %}
  <p>New tweet</p>
  <form method="POST">
  {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}